name: Master CI

on:
  push:
    branches: 
      - 'master'

jobs:
  build_all:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
      
    - name: Build
      run: dotnet build --configuration Release

  generate_version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Generate version and save it to file
      shell: bash
      run: |
        echo $(date -u +%Y.%m.%d.%k%M%S) | tee version.txt
        
    - name: Upload version - Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: version
        path: version.txt
  
  generate_release:
    runs-on: ubuntu-latest
    needs: [build_all, generate_version]
    
    steps:
    - name: Download version - Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: version
        path: temp_artf/version

    - name: Provide version from predecessor
      id: versionprovider
      run: echo "::set-output name=version::$(cat temp_artf/version/version.txt)"
          
    - name: Create Release (draft)
      id: create_draft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.versionprovider.outputs.version }}
        release_name: v${{ steps.versionprovider.outputs.version }}
        draft: true
        
    - name: Save Asset Upload URL to File
      shell: bash
      run: |
        echo '${{ steps.create_draft.outputs.upload_url }}' > asset_upload_url.txt

    - name: Upload Asset Upload URL - Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: asset_upload_url
        path: asset_upload_url.txt
  
  build_each:
    runs-on: ubuntu-latest
    needs: [generate_release]
    
    strategy:
      fail-fast: true
      matrix:
        project: 
        - "CoreFramework.Base"
        - "CoreFramework.Config"
        - "CoreFramework.Config.Json" 
        - "CoreFramework.Config.Yaml" 
        - "CoreFramework.CrashLogging"
        - "CoreFramework.Logging"
    
    steps:    
    - uses: actions/checkout@v2
      
    - name: Download version - Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: version
        path: temp_artf/version

    - name: Provide version from predecessor
      id: versionprovider
      run: echo "::set-output name=version::$(cat temp_artf/version/version.txt)"
    
    - name: Download Asset Upload URL - Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: asset_upload_url
        path: temp_artf/asset_upload_url

    - name: Fake steps.create_draft.outputs.upload_url from predecessor
      id: create_draft
      run: echo "::set-output name=upload_url::$(cat temp_artf/asset_upload_url/asset_upload_url.txt)"
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
            
    - name: Pack
      working-directory: ${{ matrix.project }}
      run: |
        dotnet pack --configuration Release -p:PackageVersion=${{ steps.versionprovider.outputs.version }} -p:AssemblyVersion=${{ steps.versionprovider.outputs.version }} -p:AssemblyInformationalVersion=${{ steps.versionprovider.outputs.version }} -p:AssemblyFileVersion=${{ steps.versionprovider.outputs.version }} -p:PathMap="$GITHUB_WORKSPACE=/"
            
    - name: Find nupkg file
      id: nupkgvar
      working-directory: ${{ matrix.project }}/bin/Release
      run: files=( *.nupkg) && echo ::set-output name=filename::$(echo "${files[0]}")
      
    - name: Upload nupkg - Upload asset
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.nupkgvar.outputs.filename }}
        path: ${{ matrix.project }}/bin/Release/${{ steps.nupkgvar.outputs.filename }}
        
    - name: Find snupkg file
      id: snupkgvar
      working-directory: ${{ matrix.project }}/bin/Release
      run: files=( *.snupkg) && echo ::set-output name=filename::$(echo "${files[0]}")
      
    - name: Upload snupkg - Upload asset
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.snupkgvar.outputs.filename }}
        path: ${{ matrix.project }}/bin/Release/${{ steps.snupkgvar.outputs.filename }}

    - name: Release - Upload nupkg
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_draft.outputs.upload_url }} 
        asset_path: ${{ matrix.project }}/bin/Release/${{ steps.nupkgvar.outputs.filename }}
        asset_name: ${{ steps.nupkgvar.outputs.filename }}
        asset_content_type: application/octet-stream
        
    - name: Release - Upload snupkg
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_draft.outputs.upload_url }} 
        asset_path: ${{ matrix.project }}/bin/Release/${{ steps.snupkgvar.outputs.filename }}
        asset_name: ${{ steps.snupkgvar.outputs.filename }}
        asset_content_type: application/octet-stream

    - name: Release - Upload nupkg (includes snupkg) to nuget.org
      working-directory: ${{ matrix.project }}/bin/Release
      run: dotnet nuget push ${{ steps.nupkgvar.outputs.filename }} -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
