name: Master Test CI

on:
  push:
    branches: 
      - 'master-release-test'

jobs:
  build_release:
    name: Build and publish test file
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
      
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Pack
      working-directory: CoreFrameworkBase
      run: dotnet pack --configuration Release -p:VersionSuffix=dev
      
    - name: Find nupkg file
      id: nupkgvar
      working-directory: CoreFrameworkBase/bin/Release
      run: files=( *.nupkg) && echo ::set-output name=filename::$(echo "${files[0]}")
      
    - name: Upload nupkg to artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.nupkgvar.outputs.filename }}
        path: CoreFrameworkBase/bin/Release/${{ steps.nupkgvar.outputs.filename }}
        
    - name: Find snupkg file
      id: snupkgvar
      working-directory: CoreFrameworkBase/bin/Release
      run: files=( *.snupkg) && echo ::set-output name=filename::$(echo "${files[0]}")
      
    - name: Upload snupkg - Upload asset
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ steps.snupkgvar.outputs.filename }}
        path: CoreFrameworkBase/bin/Release/${{ steps.snupkgvar.outputs.filename }}
            
    - name: Release - Upload nupkg (includes snupkg) to nuget.org
      working-directory: CoreFrameworkBase/bin/Release
      run: dotnet nuget push ${{ steps.nupkgvar.outputs.filename }} -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
